# Generated by Django 5.2.10 on 2026-01-30 00:36

from django.db import migrations
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('oel_sections', '0001_initial'),
    ]

    operations = [
        SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='sectionversion',
                    name='container_version',
                ),
                migrations.DeleteModel(
                    name='Section',
                ),
                migrations.DeleteModel(
                    name='SectionVersion',
                ),
            ]
        ),
    ]
