# Generated by Django 5.2.10 on 2026-01-30 00:36

from django.db import migrations
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0005_alter_collection_options_alter_collection_enabled'),
    ]

    operations = [
        SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='collectionpublishableentity',
                    name='collection',
                ),
                migrations.RemoveField(
                    model_name='collectionpublishableentity',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='collectionpublishableentity',
                    name='entity',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='entities',
                ),
                migrations.AlterModelOptions(
                    name='collection',
                    options={},
                ),
                migrations.RemoveConstraint(
                    model_name='collection',
                    name='oel_coll_uniq_lp_key',
                ),
                migrations.RemoveIndex(
                    model_name='collection',
                    name='oel_collect_learnin_dfaf89_idx',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='created',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='enabled',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='key',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='learning_package',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='modified',
                ),
                migrations.RemoveField(
                    model_name='collection',
                    name='title',
                ),
                migrations.DeleteModel(
                    name='CollectionPublishableEntity',
                ),
            ]
        ),
    ]
